[package]
name = "tcpserv08"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
socket2 = "0.4.4"
nix = "0.24.1"
libc = "0.2"
sscanf = "0.3.1"
sprintf = "0.1.2"